"""
Build script for Lemiex QC App - Creates standalone EXE files
Uses PyInstaller to create single executable for each role
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path
from datetime import datetime

# Configuration
APP_NAME = "LemiexQC"
VERSION = "1.0.0"
BUILD_DIR = Path("dist")
SPEC_DIR = Path("build_specs")

# Roles to build (Packing temporarily hidden)
ROLES = [
    ("QC", 8081, "green"),
    # ("Packing", 8082, "orange"),  # Hidden temporarily
    ("Shipout", 8083, "blue"),
]

# Icon path - use logo folder
ICON_PATH = Path("logo/lemiex.ico")

# Data files to include
DATA_FILES = [
    ("web", "web"),
    ("config", "config"),
    ("updater", "updater"),
]

# Hidden imports that PyInstaller might miss
HIDDEN_IMPORTS = [
    "eel",
    "bottle_websocket",
    "gevent",
    "geventwebsocket",
    "geventwebsocket.handler",
    "cv2",
    "numpy",
    "qrcode",
    "PIL",
    "PIL.Image",
    "PIL.ImageDraw", 
    "PIL.ImageFont",
    "requests",
    "dotenv",
    "httpx",
    "win32print",
    "win32api",
    "win32con",
    "core",
    "core.api_client",
    "core.auth_manager",
    "models",
    "models.order",
    "services",
    "services.order_service",
    "services.b2_uploader",
    "scanner",
    "scanner.qr_scanner",
    "camera",
    "camera.recorder",
]


def check_pyinstaller():
    """Check if PyInstaller is installed"""
    try:
        import PyInstaller
        print(f"✓ PyInstaller {PyInstaller.__version__} found")
        return True
    except ImportError:
        print("✗ PyInstaller not found. Installing...")
        subprocess.run([sys.executable, "-m", "pip", "install", "pyinstaller"], check=True)
        return True


def clean_build():
    """Clean previous build artifacts"""
    print("\nCleaning previous builds...")
    
    dirs_to_clean = ["build", "dist", "build_specs"]
    for d in dirs_to_clean:
        path = Path(d)
        if path.exists():
            shutil.rmtree(path)
            print(f"  ✓ Removed {d}/")
    
    # Remove old spec files
    for spec in Path(".").glob("*.spec"):
        spec.unlink()
        print(f"  ✓ Removed {spec}")
    
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    SPEC_DIR.mkdir(parents=True, exist_ok=True)


def create_icon():
    """Create a simple icon if not exists"""
    if not ICON_PATH.exists():
        print("  ⚠ Icon not found, using default")
        return None
    return str(ICON_PATH)


def create_spec_file(role_name, port):
    """Create PyInstaller spec file for a role"""
    icon = create_icon()
    icon_line = f"icon='{icon}'," if icon else ""
    
    # Build data files string
    datas = []
    for src, dst in DATA_FILES:
        if Path(src).exists():
            datas.append(f"('{src}', '{dst}')")
    datas_str = ",\n        ".join(datas)
    
    # Build hidden imports string
    hidden_str = ",\n        ".join([f"'{h}'" for h in HIDDEN_IMPORTS])
    
    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for Lemiex {role_name}
# Auto-generated by build_exe.py

block_cipher = None

a = Analysis(
    ['app_eel.py'],
    pathex=[],
    binaries=[],
    datas=[
        {datas_str}
    ],
    hiddenimports=[
        {hidden_str}
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Lemiex_{role_name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window (GUI app)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    {icon_line}
)
'''
    
    spec_path = SPEC_DIR / f"Lemiex_{role_name}.spec"
    with open(spec_path, 'w') as f:
        f.write(spec_content)
    
    print(f"  ✓ Created {spec_path}")
    return spec_path


def create_wrapper_script(role_name, port):
    """Create a wrapper Python script that passes role argument"""
    wrapper_content = f'''#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Wrapper script for Lemiex {role_name}
Auto-starts with --role {role_name} argument
"""
import sys
sys.argv.extend(['--role', '{role_name}'])

# Import and run main app
from app_eel import main
if __name__ == "__main__":
    main()
'''
    
    wrapper_path = Path(f"_wrapper_{role_name.lower()}.py")
    with open(wrapper_path, 'w') as f:
        f.write(wrapper_content)
    
    return wrapper_path


def build_exe_simple(role_name, port):
    """Build EXE using simple PyInstaller command"""
    print(f"\n{'='*50}")
    print(f"Building Lemiex_{role_name}.exe...")
    print(f"{'='*50}")
    
    # Create wrapper script
    wrapper = create_wrapper_script(role_name, port)
    
    # Build command
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",           # Single EXE file
        "--windowed",          # No console window
        "--clean",             # Clean cache
        f"--name=Lemiex_{role_name}",
        "--add-data=web;web",
        "--add-data=config;config",
    ]
    
    # Add optional folders if they exist
    optional_folders = ["updater", "core", "models", "services", "scanner", "camera"]
    for folder in optional_folders:
        if Path(folder).exists():
            cmd.append(f"--add-data={folder};{folder}")
    
    # Add hidden imports
    for imp in HIDDEN_IMPORTS:
        cmd.append(f"--hidden-import={imp}")
    
    # Add icon if exists
    if ICON_PATH.exists():
        cmd.append(f"--icon={ICON_PATH}")
    
    # Add the wrapper script
    cmd.append(str(wrapper))
    
    print(f"\nRunning: {' '.join(cmd[:5])}...")
    
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        print(f"✓ Lemiex_{role_name}.exe built successfully!")
        
        # Move to dist with version
        src = BUILD_DIR / f"Lemiex_{role_name}.exe"
        if src.exists():
            print(f"  Size: {src.stat().st_size / (1024*1024):.1f} MB")
        
        return True
        
    except subprocess.CalledProcessError as e:
        print(f"✗ Build failed!")
        print(f"  Error: {e.stderr}")
        return False
    
    finally:
        # Cleanup wrapper
        if wrapper.exists():
            wrapper.unlink()


def build_all_roles():
    """Build EXE for all roles"""
    print("\n" + "="*60)
    print(f"  Building Lemiex QC App v{VERSION}")
    print(f"  Target: Standalone EXE files")
    print(f"  Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("="*60)
    
    # Check PyInstaller
    if not check_pyinstaller():
        return False
    
    clean_build()
    
    success_count = 0
    for role_name, port, color in ROLES:
        if build_exe_simple(role_name, port):
            success_count += 1
    
    # Summary
    print("\n" + "="*60)
    print("  BUILD SUMMARY")
    print("="*60)
    print(f"\n✓ Built {success_count}/{len(ROLES)} executables:")
    
    for role_name, port, color in ROLES:
        exe_path = BUILD_DIR / f"Lemiex_{role_name}.exe"
        if exe_path.exists():
            size = exe_path.stat().st_size / (1024*1024)
            print(f"  📦 Lemiex_{role_name}.exe ({size:.1f} MB) - Port {port}")
        else:
            print(f"  ✗ Lemiex_{role_name}.exe - FAILED")
    
    print(f"\n📁 Output folder: {BUILD_DIR.absolute()}")
    print("\n💡 To run: Double-click the EXE file")
    print("   Each role runs on its own port automatically")
    
    return success_count == len(ROLES)


def create_combined_exe():
    """Build a single EXE with role selection dialog"""
    print("\n" + "="*50)
    print("Building combined LemiexQC.exe with role selector...")
    print("="*50)
    
    # Create launcher script with role selection
    launcher_content = '''#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Lemiex QC App - Combined Launcher
Shows role selection dialog on startup
"""
import sys
import tkinter as tk
from tkinter import ttk

def select_role():
    """Show role selection dialog"""
    root = tk.Tk()
    root.title("Lemiex QC - Chọn vai trò")
    root.geometry("300x200")
    root.resizable(False, False)
    
    # Center window
    root.eval('tk::PlaceWindow . center')
    
    selected_role = tk.StringVar(value="QC")
    
    tk.Label(root, text="LEMIEX QC", font=("Arial", 16, "bold")).pack(pady=10)
    tk.Label(root, text="Chọn vai trò:", font=("Arial", 10)).pack(pady=5)
    
    roles = [
        ("QC - Kiểm tra chất lượng", "QC"),
        ("Shipout - Xuất hàng", "Shipout"),
    ]
    
    for text, value in roles:
        ttk.Radiobutton(root, text=text, value=value, variable=selected_role).pack(anchor="w", padx=50)
    
    def start_app():
        root.destroy()
        sys.argv.extend(['--role', selected_role.get()])
        from app_eel import main
        main()
    
    ttk.Button(root, text="Bắt đầu", command=start_app).pack(pady=20)
    
    root.mainloop()

if __name__ == "__main__":
    # Check if role already specified
    if '--role' in sys.argv:
        from app_eel import main
        main()
    else:
        select_role()
'''
    
    launcher_path = Path("_launcher.py")
    with open(launcher_path, 'w', encoding='utf-8') as f:
        f.write(launcher_content)
    
    # Build command
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",
        "--windowed",
        "--clean",
        "--name=LemiexQC",
        "--add-data=web;web",
        "--add-data=config;config",
    ]
    
    # Add optional folders
    optional_folders = ["updater", "core", "models", "services", "scanner", "camera"]
    for folder in optional_folders:
        if Path(folder).exists():
            cmd.append(f"--add-data={folder};{folder}")
    
    # Add hidden imports
    for imp in HIDDEN_IMPORTS:
        cmd.append(f"--hidden-import={imp}")
    
    # Add tkinter for dialog
    cmd.extend(["--hidden-import=tkinter", "--hidden-import=tkinter.ttk"])
    
    # Add icon if exists
    if ICON_PATH.exists():
        cmd.append(f"--icon={ICON_PATH}")
    
    cmd.append(str(launcher_path))
    
    try:
        subprocess.run(cmd, check=True)
        print(f"✓ LemiexQC.exe built successfully!")
        
        exe_path = BUILD_DIR / "LemiexQC.exe"
        if exe_path.exists():
            print(f"  Size: {exe_path.stat().st_size / (1024*1024):.1f} MB")
        
        return True
        
    except subprocess.CalledProcessError as e:
        print(f"✗ Build failed: {e}")
        return False
        
    finally:
        # Cleanup
        if launcher_path.exists():
            launcher_path.unlink()


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Build Lemiex QC as standalone EXE")
    parser.add_argument("--combined", action="store_true", 
                        help="Build single EXE with role selector dialog")
    parser.add_argument("--separate", action="store_true", 
                        help="Build separate EXE for each role (default)")
    parser.add_argument("--all", action="store_true",
                        help="Build both combined and separate EXEs")
    
    args = parser.parse_args()
    
    if args.all:
        build_all_roles()
        create_combined_exe()
    elif args.combined:
        check_pyinstaller()
        clean_build()
        create_combined_exe()
    else:
        # Default: build separate EXEs
        build_all_roles()
